### ISSUE TITLE
Auto corpse pick up ? 

### ISSUE THREAD

**Issue by Eneitilyn** [ryunp/d2qol#2]
I am not sure if you accept suggestions or ideas but..
Is this possible with AHK ? Since it seems like MarcoNecroX has no intention of fixing corpses spawning right under portal any time soon or its been already fixed its just the update is not applied into "non sigma versions" Since corpses always seem to spawn at the same spot in town I wouldn't think this would be too hard to do automatically?

**Comment by ryunp** [comment]
Yes! Ideas are always welcome! I don't have much interest in this feature at the moment with the reason being major changes coming in MXL: Sigma that should resolve this issue.

Consider using the official Median XL forum thread for posting ideas and suggestions! Also feel free to use Discord to bounce ideas around in real time.

Cheers!

**Comment by ryunp** [comment]
I have not looked into the possible solution path mainly due to MXL: Sigma addressing many issues including this one.

Suggestions and cirticism is always welcome! Consider using the offiicial [Median XL Forum thread](Appriciate the ) for discussing further ideas, or hit me up in [Median XL discord](https://discordapp.com/invite/UA2ZAdX)!

**Comment by ryunp** [comment]
I have not looked into the possible solution path mainly due to MXL: Sigma addressing this issue.

Suggestions and criticism are always welcome! Consider using the official [Median XL Forum thread](https://forum.median-xl.com/viewtopic.php?f=4&t=3302&sid=a2d830fa9aefb97dcc5264fc48caab65) for discussing further ideas, or hit me up in [Median XL discord](https://discordapp.com/invite/UA2ZAdX)!
